Repository SHPE-at-UCI/shpesignin, pull requests merged in 2020-02, with the labels that each got.

#11 fixed base.html and thank you skeleton
  app.py
  templates/base.html
  templates/thank-you.html
Labels: front end, good first issue

#13 updated bootstrap home page
  templates/home.html
Labels: front end

#14 feat(thank-you.html): added typography
  templates/thank-you.html
Labels: enhancement, front end
